name: Despliegue y Pruebas Continuas de la App Barbería

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar el código fuente del repositorio
      uses: actions/checkout@v4

    - name: Configurar Entorno de Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar la Aplicación y Ejecutar Pruebas
      run: |
        echo "Iniciando compilación automática del Backend..."
        javac -d bin src/com/barberia/model/Reserva.java src/com/barberia/controller/GestorReservas.java src/com/barberia/test/GestorReservasTest.java
        echo "Compilación exitosa. Ejecutando tests del sistema..."
        java -cp bin com.barberia.test.GestorReservasTest